// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search': string;
  'btns': string;
  'fNewLine': string;
  'searchBtn': string;
}
export const cssExports: CssExports;
export default cssExports;
